[project]
name = "langgraph-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langgraph>=0.5.4",
    "notebook>=7.4.4",
    "python-dotenv>=1.1.1",
]
